name: PlayerBuff
version: '${project.version}'
main: azuazu3939.playerbuff.PlayerBuff
api-version: 1.15

commands:
  playerbuff:
    permission: playerbuff.command.reload
    description: "playerbuffのreloadコマンド。"
  pbs:
    permission: playerbuff.command.pbs
    description: "playerbuffでbuffをセットする実行部分。"